### PR TITLE
feat: transparency with `winblend`

### PR DESCRIPTION
**Pull request by axieax**
This PR adds the ability to specify a `winblend` for the editor window.

### CODE REVIEW

**Comment by AckslD** [comment]
Hi @axieax, couldn't you do this in the `post_open_float` callback setting?

**Comment by axieax** [comment]
Good point! I've updated this PR to include the win number which was missing from the hook.

**Comment by AckslD** [comment]
Cool, this looks good and I'm happy to merge it if it's useful for you. But just for my understanding, could you also use `vim.fn.winnr` in the `post_open_float` to get the window number?

**Comment by axieax** [comment]
`vim.fn.winnr()` doesn't seem to work for some reason - it returns a different number to the `winnr` passed in. Good to merge this though, so it'll be easier for users to know that winoptions can be configured with the `post_open_float` hook with it passed in!

**Pull request merged**
